### ISSUE TITLE
StartTag: invalid element name

### ISSUE THREAD

**Issue by giuseppec** [jimhester/lintr#275]
With the github version I get:
```
> lint_package()
.Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  StartTag: invalid element name [68]
> traceback()
18: stop(list(message = "StartTag: invalid element name [68]", call = doc_parse_raw(x, 
        encoding = encoding, base_url = base_url, as_html = as_html, 
        options = options), cppstack = list(file = "", line = -1L, 
        stack = "C++ stack not available on this system")))
17: .Call("_xml2_doc_parse_raw", PACKAGE = "xml2", x, encoding, base_url, 
        as_html, options)
16: doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html, 
        options = options)
15: read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html, 
        options = options)
14: read_xml.character(xmlparsedata::xml_parse_data(pc))
13: xml2::read_xml(xmlparsedata::xml_parse_data(pc))
12: FUN(X[[i]], ...)
11: lapply(top_level_expressions(parsed_content), function(loc) {
        line_nums <- parsed_content$line1[loc]:parsed_content$line2[loc]
        expr_lines <- source_file$lines[line_nums]
        names(expr_lines) <- line_nums
        content <- get_content(expr_lines, parsed_content[loc, ])
        id <- as.character(parsed_content$id[loc])
        edges <- component_edges(tree, id)
        pc <- parsed_content[c(loc, edges), ]
        list(filename = filename, line = parsed_content[loc, "line1"], 
            column = parsed_content[loc, "col1"], lines = expr_lines, 
            parsed_content = pc, xml_parsed_content = xml2::read_xml(xmlparsedata::xml_parse_data(pc)), 
            content = content, find_line = find_line_fun(content), 
            find_column = find_column_fun(content))
    })
10: get_source_expressions(filename)
9: lint(file, ..., parse_settings = FALSE, exclusions = exclusions)
8: FUN(X[[i]], ...)
7: lapply(files, function(file) {
       if (interactive()) {
           message(".", appendLF = FALSE)
       }
       lint(file, ..., parse_settings = FALSE, exclusions = exclusions)
   })
6: inherits(x, class)
5: assign_item(x)
4: flatten_list(x, class = "lint")
3: structure(flatten_list(x, class = "lint"), class = "lints")
2: flatten_lints(lapply(files, function(file) {
       if (interactive()) {
           message(".", appendLF = FALSE)
       }
       lint(file, ..., parse_settings = FALSE, exclusions = exclusions)
   }))
1: lint_package()
```
The CRAN lintr version works fine.
I have tried both, the xml2 package from CRAN and also from github,s

**Comment by LiNk-NY** [comment]
Hi Jim, @jimhester 

I'm also getting this issue from the wercker step.
```yaml
    - jimhester/r-lint
```
Is there a way to use the `CRAN` lintr version?
I've tried to install it in a `script` step:

```yaml
  steps:
    - script:
        name: Install devtools and lintr
        code: R -e "install.packages(c('devtools', 'lintr'))"
```

but this didn't work for me. It somehow has the GitHub version already installed.

```
>> wercker build
[truncated]...
Skipping install of 'lintr' from a github remote, the SHA1 (fe5de83b) has not changed since last install.
  Use `force = TRUE` to force installation
```

This is my `wercker.yml`:

```yaml
box: bioconductor/devel_core2
build:
  steps:
    - script:
        name: Install devtools and lintr
        code: R -e "install.packages(c('devtools', 'lintr'))"
    - jimhester/r-dependencies
    - jimhester/r-check
    - mr148/r-lint
    - jimhester/r-coverage
```

I've made a minor modification to the [wercker-step-lint-r](https://github.com/LiNk-NY/wercker-step-r-lint/commit/0b06a24609396193c0181345c63b12fd20b77865) here (removed the lintr GitHub installation).

Thanks, 
Marcel
