### ISSUE TITLE
Failed with CircleCI 2.0

### ISSUE THREAD

**Issue by angrygoats** [jimhester/lintr#300]
After reading [this](https://github.com/jimhester/lintr/issues/166) issue on Gitlab I tried to fix this error by overwriting the `CI` environment variable. Unfortunately, it still fails. Circle fails with this message:

```
test_lints.R:4: error: Package Style
object 'response' not found
1: lintr::expect_lint_free() at /root/main/tests/testthat/test_lints.R:4
2: paste(collapse = "\n", capture.output(print(lints)))
3: capture.output(print(lints))
4: evalVis(expr)
5: withVisible(eval(expr, pf))
6: eval(expr, pf)
7: eval(expr, pf)
8: print(lints)
9: print.lints(lints)
10: github_comment(lint_output, info, ...)
11: httr::status_code(response)
────────────────────────────────
```

I tried to remedy this by using the following CircleCI configuration:

```yaml
version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: appsilon/ci-base:1.0
    steps:
      - checkout
      - run:
          command: |
            R -e 'devtools:::install_deps(dependencies = TRUE)'

      - run:
          command: |
            R -e 'devtools::install_github("jimhester/lintr")'
      - run:
          command: |
            R -e 'devtools::check()'
      - run:
          command: |
            export CI=""
          command: |
            R -e 'devtools::test()'
      - store_artifacts:
          path: man/
          destination: man
```

Unfortunately it is still failing. Is there a way around this?
