### ISSUE TITLE
Error when running GH action - 

### ISSUE THREAD

**Issue by chrisumphlett** [jimhester/lintr#798]
I'm not sure even where to begin on troubleshooting this on my own as I don't know much about GH actions and the whys and whats of the .yaml file.

I'm getting an error in the workflow that I think is related to the install of remotes. The output below is from the job summary in my repo:

![image](https://user-images.githubusercontent.com/7210482/118041937-6ee9e300-b341-11eb-8404-6748fa848450.png)

```
Run install.packages('remotes')
  install.packages('remotes')
  saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
  writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
  shell: /usr/local/bin/Rscript {0}
  env:
    GITHUB_PAT: ***
    R_LIBS_USER: /Users/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
Installing package into ‘/Users/runner/work/_temp/Library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/bin/macosx/contrib/4.0/remotes_2.3.0.tgz'
Content type 'application/x-gzip' length 390609 bytes (381 KB)
==================================================
downloaded 381 KB


The downloaded binary packages are in
	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//RtmpUDKQ5G/downloaded_packages
Error: Error in read.dcf(path) : cannot open the connection
Calls: saveRDS ... load_pkg_description -> read_dcf -> colnames -> is.data.frame -> read.dcf
In addition: Warning message:
In read.dcf(path) :
  cannot open compressed file '/Users/runner/work/Org_Engagement/Org_Engagement/DESCRIPTION', probable reason 'No such file or directory'
Execution halted
Error: Process completed with exit code 1.
```

**Comment by MichaelChirico** [comment]
Hi @chrisumphlett, any reason to believe this is a `lintr` issue? At a glance, it looks like the most likely culprit is `remotes::dev_package_deps()`.

**Comment by chrisumphlett** [comment]
No not directly. It's an issue with me trying to understand and troubleshoot using `lintr` via GH Actions. My ignorance is making it difficult to diagnose. 

This line seems to imply that "Org Engagement" is a package? 
` cannot open compressed file '/Users/runner/work/Org_Engagement/Org_Engagement/DESCRIPTION', probable reason 'No such file or directory'`

This repo is not a package. It contains various analysis, data, and shiny app scripts.

**Comment by dragosmg** [comment]
Apologies for jumping in. It's difficult to diagnose without having access to the GitHub Actions workflow YAML file. If you are using the standard {lintr} GitHub Action (as defined [here](https://github.com/r-lib/actions/blob/master/examples/lint.yaml)), it assumes you're trying to lint a package and, as a consequence, it uses `lintr::lint_package()`. The package needs to be installed first, hence the steps to figure out and install dependencies before installing the package.  

If you're not linting a package, you need a much simpler GitHub Action, one that installs {lintr} and runs lint either on a file (`lintr::lint(file_path)`)or a directory (`lintr::lint_dir(dir_path)`). If you feel like trying this approach, you can have a look at this file - https://github.com/jimhester/lintr/blob/master/.github/workflows/test-coverage.yaml - you can safely remove the _query dependencies_, _cache R packages_ and _install dependencies steps_, resulting in something similar to this:

```
on:
  push:
    branches:
      - main
      - master
      - '**'
  pull_request:
    branches:
      - main
      - master

name: lint

jobs:
  lint:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install lintr
        run: |
          install.packages("remotes")
          remotes::install_cran("lintr")
        shell: Rscript {0}

      - name: Lint
        run: lintr::lint_dir()
        shell: Rscript {0}
```
